/*** Generated by streamline --lines-mark 0.1.9 - DO NOT EDIT ***/

var __global = typeof global !== 'undefined' ? global : window;
function __cb(_, fn) { var ctx = __global.__context; return function(err, result) { __global.__context = ctx; if (err) return _(err); return fn(null, result); } }
function __propagate(_, err) { try { _(err); } catch (ex) { __trap(ex); } }
function __trap(err) { if (err) { if (__global.__context && __global.__context.errorHandler) __global.__context.errorHandler(err); else console.error("UNCAUGHT EXCEPTION: " + err.message + "\n" + err.stack); } }
            (function(_) {
              var __ = (_ = (_ || __trap));
/*    51 */   function getNodeId(url) {
/*    52 */     var NODE_REGEX = /node\/(\d+)/g;
/*    53 */     var match = NODE_REGEX.exec(url);
/*    54 */     return (match ? parseInt(match[1]) : null);
              };
/*     5 */   var assert = require("assert");
/*     6 */   var db = require("./setup");
/*     9 */   var data = {
/*    10 */     name: "Daniel Gasienica",
/*    11 */     magicNumber: 42,
/*    12 */     lovesIceCream: true
              };
/*    14 */   var newData = {
/*    15 */     name: "Daniel Gasienica",
/*    16 */     father: {
/*    17 */       firstName: "Jan",
/*    18 */       lastName: "Gasienica"
                },
/*    20 */     tired: false
              };
/*    29 */   return db.createNode(data, __cb(_, function(__0, url1) {
/*    30 */     var id = getNodeId(url1);
/*    32 */     return db.getNode(id, __cb(_, function(__0, res2) {
/*    33 */       assert.deepEqual(res2, data, "Retrieved data does not match original data.");
/*    35 */       return db.updateNode(id, newData, __cb(_, function(__0, res3) {
/*    36 */         return db.getNode(id, __cb(_, function(__0, res4) {
/*    37 */           assert.deepEqual(res4, newData, "Retrieved data does not match updated data.");
/*    39 */           return db.deleteNode(id, __cb(_, function() {
                        return function(__) {
                          return function(_) {
                            try {
/*    42 */                   return db.getNode(id, __cb(_, function() {
/*    43 */                     assert.fail("Found node even though it was deleted.");
                                return __();
                              }));
                            } catch (e) {
                              return __propagate(_, e);
                            };
                          }(function(err, __result) {
                            try {
                              if (err) {
/*    45 */                     assert.strictEqual(err.statusCode, 404, "Nonexistent node returned non-404 error.");
                              }
                               else return _(null, __result)
                            ;
                            } catch (e) {
                              return __propagate(_, e);
                            };
                            return __();
                          });
                        }(function() {
                          try {
                            return __();
                          } catch (e) {
                            return __propagate(_, e);
                          };
                        });
                      }));
                    }));
                  }));
                }));
              }));
            })();
