/*** Generated by streamline --lines-mark 0.1.9 - DO NOT EDIT ***/

var __global = typeof global !== 'undefined' ? global : window;
/*     1 */ var assert = require("assert");
/*     6 */ var db = require("./setup");
/*     7 */ var neo4j = require("../lib/neo4j");
/*    10 */ var data = {
/*    11 */   name: "Daniel Gasienica",
/*    12 */   magicNumber: 42,
/*    13 */   lovesIceCream: true
            };
/*    15 */ var newData = {
/*    16 */   name: "Daniel Gasienica",
/*    17 */   father: {
/*    18 */     firstName: "Jan",
/*    19 */     lastName: "Gasienica"
              },
/*    21 */   tired: false
            };
/*    26 */ function transform(o) {
/*    27 */   return neo4j.deserialize(neo4j.serialize(o));
            };
/*    30 */ assert.deepEqual(transform(data), data);
/*    31 */ assert.deepEqual(transform(newData), newData);
/*    33 */ var o;
/*    36 */ o = 1;
/*    37 */ assert.strictEqual(transform(o), o);
/*    40 */ o = "gasi";
/*    41 */ assert.strictEqual(transform(o), o);
/*    44 */ o = true;
/*    45 */ assert.strictEqual(transform(o), o);
/*    48 */ o = [true,false,true,];
/*    49 */ assert.throws(transform(o));
/*    52 */ o = {
/*    52 */   "this.that": "shouldn't work"
            };
/*    53 */ assert.notDeepEqual(transform(o), o);
