/*** Generated by streamline --lines-mark 0.1.9 - DO NOT EDIT ***/

var __global = typeof global !== 'undefined' ? global : window;
function __cb(_, fn) { var ctx = __global.__context; return function(err, result) { __global.__context = ctx; if (err) return _(err); return fn(null, result); } }
function __propagate(_, err) { try { _(err); } catch (ex) { __trap(ex); } }
function __trap(err) { if (err) { if (__global.__context && __global.__context.errorHandler) __global.__context.errorHandler(err); else console.error("UNCAUGHT EXCEPTION: " + err.message + "\n" + err.stack); } }
            (function(_) {
              var __ = (_ = (_ || __trap));
/*   108 */   function getNodeId(url) {
/*   109 */     var NODE_REGEX = /node\/(\d+)/g;
/*   110 */     var match = NODE_REGEX.exec(url);
/*   111 */     return (match ? parseInt(match[1]) : null);
              };
/*     4 */   var assert = require("assert");
/*     5 */   var neo4j = require("../lib/neo4j.js");
/*     8 */   var DB_HOST = "localhost";
/*     9 */   var DB_PORT = 7474;
/*    10 */   var db = new neo4j.Client(DB_HOST, DB_PORT, true);
/*    13 */   var data = {
/*    14 */     name: "Daniel Gasienica",
/*    15 */     magicNumber: 42,
/*    16 */     lovesIceCream: true
              };
/*    18 */   var newData = {
/*    19 */     name: "Daniel Gasienica",
/*    20 */     father: {
/*    21 */       firstName: "Jan",
/*    22 */       lastName: "Gasienica"
                },
/*    24 */     tired: false
              };
/*    31 */   console.log("Running tests...");
/*    39 */   return db.createNode(data, __cb(_, function(__0, url1) {
/*    40 */     var id = getNodeId(url1);
/*    42 */     return db.getNode(id, __cb(_, function(__0, res2) {
/*    43 */       assert.deepEqual(res2, data, "Retrieved data does not match original data.");
/*    45 */       return db.updateNode(id, newData, __cb(_, function(__0, res3) {
/*    46 */         return db.getNode(id, __cb(_, function(__0, res4) {
/*    47 */           assert.deepEqual(res4, newData, "Retrieved data does not match updated data.");
/*    49 */           return db.deleteNode(id, __cb(_, function() {
                        return function(__) {
                          return function(_) {
                            try {
/*    52 */                   return db.getNode(id, __cb(_, function() {
/*    53 */                     assert.fail("Found node even though it was deleted.");
                                return __();
                              }));
                            } catch (e) {
                              return __propagate(_, e);
                            };
                          }(function(err, __result) {
                            try {
                              if (err) {
/*    55 */                     assert.strictEqual(err.statusCode, 404, "Nonexistent node returned non-404 error.");
                              }
                               else return _(null, __result)
                            ;
                            } catch (e) {
                              return __propagate(_, e);
                            };
                            return __();
                          });
                        }(function() {
                          try {
/*    61 */                 function transform(o) {
/*    62 */                   return neo4j.deserialize(neo4j.serialize(o));
                            };
/*    65 */                 assert.deepEqual(transform(data), data);
/*    66 */                 assert.deepEqual(transform(newData), newData);
/*    68 */                 var o;
/*    71 */                 o = 1;
/*    72 */                 assert.strictEqual(transform(o), o);
/*    75 */                 o = "gasi";
/*    76 */                 assert.strictEqual(transform(o), o);
/*    79 */                 o = true;
/*    80 */                 assert.strictEqual(transform(o), o);
/*    83 */                 o = [true,false,true,];
/*    84 */                 assert.throws(transform(o));
/*    87 */                 o = {
/*    87 */                   "this.that": "shouldn't work"
                            };
/*    88 */                 assert.notDeepEqual(transform(o), o);
/*    99 */                 console.log("Finished running tests.");
/*   104 */                 function print(error, result) {
/*   105 */                   console.log(((error || result) || ""));
                            };
                            return __();
                          } catch (e) {
                            return __propagate(_, e);
                          };
                        });
                      }));
                    }));
                  }));
                }));
              }));
            })();
