/*** Generated by streamline 0.4.5 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__tryCatch=__rt.__tryCatch; (function() {
  var GraphDatabase, Node, Relationship, adjustError, status, util;

  status = require("http-status");

  util = require("./util");

  adjustError = util.adjustError;

  Relationship = require("./Relationship");

  Node = require("./Node");

  module.exports = GraphDatabase = (function() {
    var _this = this;

    function GraphDatabase(opts) {
      opts = ((typeof opts === "string") ? {
        url: opts
      } : opts);
      this.url = opts.url;
      this._request = util.wrapRequest(opts);
      this._root = null;
      this._services = null; };






    GraphDatabase.prototype._purgeCache = function() {
      this._root = null;
      return this._services = null; };


    GraphDatabase.prototype._getRoot = function GraphDatabase_prototype__getRoot__1(_) { var response, __this = this; var __frame = { name: "GraphDatabase_prototype__getRoot__1", line: 36 }; return __func(_, this, arguments, GraphDatabase_prototype__getRoot__1, 0, __frame, function __$GraphDatabase_prototype__getRoot__1() {

        if ((__this._root != null)) {
          return _(null, __this._root); } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype__getRoot__1() {


              return __this._request.get(__this.url, __cb(_, __frame, 6, 19, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  return _(response); } ;

                return _(null, __this._root = response.body); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype__getRoot__1() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getServices = function GraphDatabase_prototype_getServices__2(_) { var response, root, __this = this; var __frame = { name: "GraphDatabase_prototype_getServices__2", line: 52 }; return __func(_, this, arguments, GraphDatabase_prototype_getServices__2, 0, __frame, function __$GraphDatabase_prototype_getServices__2() {

        if ((__this._services != null)) {
          return _(null, __this._services); } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getServices__2() {


              return __this._getRoot(__cb(_, __frame, 6, 15, function ___(__0, __1) { root = __1;
                return __this._request.get(root.data, __cb(_, __frame, 7, 19, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, __this._services = response.body); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getServices__2() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getVersion = function GraphDatabase_prototype_getVersion__3(_) { var services, __this = this; var __frame = { name: "GraphDatabase_prototype_getVersion__3", line: 69 }; return __func(_, this, arguments, GraphDatabase_prototype_getVersion__3, 0, __frame, function __$GraphDatabase_prototype_getVersion__3() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getVersion__3() {


              return __this.getServices(__cb(_, __frame, 3, 19, function ___(__0, __1) { services = __1;
                return _(null, parseFloat((services["neo4j_version"] || "1.4"))); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getVersion__3() { if (error) {

                return _(adjustError); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };







    GraphDatabase.prototype.createNode = function(data) {
      var node;
      data = (data || { });
      node = new Node(this, {
        data: data });

      return node; };


    GraphDatabase.prototype.getNode = function GraphDatabase_prototype_getNode__4(url, _) { var response, __this = this; var __frame = { name: "GraphDatabase_prototype_getNode__4", line: 92 }; return __func(_, this, arguments, GraphDatabase_prototype_getNode__4, 1, __frame, function __$GraphDatabase_prototype_getNode__4() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getNode__4() {


              return __this._request.get(url, __cb(_, __frame, 3, 19, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  if ((response.statusCode === status.NOT_FOUND)) {
                    return _(new Error(("No node at " + url))); } ;

                  return _(response); } ;

                return _(null, new Node(__this, response.body)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getNode__4() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getNodeById = function GraphDatabase_prototype_getNodeById__5(id, _) { var node, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_getNodeById__5", line: 108 }; return __func(_, this, arguments, GraphDatabase_prototype_getNodeById__5, 1, __frame, function __$GraphDatabase_prototype_getNodeById__5() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getNodeById__5() {


              return __this.getServices(__cb(_, __frame, 3, 19, function ___(__0, __1) { services = __1;
                url = ((("" + services.node) + "/") + id);
                return __this.getNode(url, __cb(_, __frame, 5, 15, function ___(__0, __2) { node = __2;
                  return _(null, node); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getNodeById__5() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getIndexedNode = function GraphDatabase_prototype_getIndexedNode__6(index, property, value, _) { var node, nodes, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedNode__6", line: 120 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedNode__6, 3, __frame, function __$GraphDatabase_prototype_getIndexedNode__6() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNode__6() {


              return __this.getIndexedNodes(index, property, value, __cb(_, __frame, 3, 16, function ___(__0, __1) { nodes = __1;
                node = null;
                if ((nodes && (nodes.length > 0))) {
                  node = nodes[0]; } ;

                return _(null, node); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNode__6() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getIndexedNodes = function GraphDatabase_prototype_getIndexedNodes__7(index, property, value, _) { var key, response, services, url, val, _this, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedNodes__7", line: 134 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedNodes__7, 3, __frame, function __$GraphDatabase_prototype_getIndexedNodes__7() { _this = __this; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNodes__7() {



              return __this.getServices(__cb(_, __frame, 4, 19, function ___(__0, __1) { services = __1;
                key = encodeURIComponent(property);
                val = encodeURIComponent(value);
                url = ((((((("" + services.node_index) + "/") + index) + "/") + key) + "/") + val);
                return __this._request.get(url, __cb(_, __frame, 8, 19, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map(function(node) {
                    return new Node(_this, node); })); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNodes__7() { if (error) {


                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.queryNodeIndex = function GraphDatabase_prototype_queryNodeIndex__8(index, query, _) { var response, services, url, _this, __this = this; var __frame = { name: "GraphDatabase_prototype_queryNodeIndex__8", line: 154 }; return __func(_, this, arguments, GraphDatabase_prototype_queryNodeIndex__8, 2, __frame, function __$GraphDatabase_prototype_queryNodeIndex__8() { _this = __this; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_queryNodeIndex__8() {



              return __this.getServices(__cb(_, __frame, 4, 19, function ___(__0, __1) { services = __1;
                url = ((((("" + services.node_index) + "/") + index) + "?query=") + (encodeURIComponent(query)));
                return __this._request.get(url, __cb(_, __frame, 6, 19, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map(function(node) {
                    return new Node(_this, node); })); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_queryNodeIndex__8() { if (error) {


                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };







    GraphDatabase.prototype.createRelationship = function GraphDatabase_prototype_createRelationship__9(startNode, endNode, type, _) { var __frame = { name: "GraphDatabase_prototype_createRelationship__9", line: 176 }; return __func(_, this, arguments, GraphDatabase_prototype_createRelationship__9, 3, __frame, _); };

    GraphDatabase.prototype.getRelationship = function GraphDatabase_prototype_getRelationship__10(url, _) { var response, __this = this; var __frame = { name: "GraphDatabase_prototype_getRelationship__10", line: 178 }; return __func(_, this, arguments, GraphDatabase_prototype_getRelationship__10, 1, __frame, function __$GraphDatabase_prototype_getRelationship__10() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getRelationship__10() {


              return __this._request.get(url, __cb(_, __frame, 3, 19, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  return _(response); } ;

                return _(null, new Relationship(__this, response.body)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getRelationship__10() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getRelationshipById = function GraphDatabase_prototype_getRelationshipById__11(id, _) { var relationshipURL, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_getRelationshipById__11", line: 191 }; return __func(_, this, arguments, GraphDatabase_prototype_getRelationshipById__11, 1, __frame, function __$GraphDatabase_prototype_getRelationshipById__11() {

        return __this.getServices(__cb(_, __frame, 2, 17, function ___(__0, __1) { services = __1;
          relationshipURL = services.node.replace("node", "relationship");
          url = ((("" + relationshipURL) + "/") + id);
          return __this.getRelationship(url, __cb(_, __frame, 5, 13, _, true)); }, true)); }); };


    GraphDatabase.prototype.getIndexedRelationship = function GraphDatabase_prototype_getIndexedRelationship__12(index, property, value, _) { var relationships, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedRelationship__12", line: 199 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedRelationship__12, 3, __frame, function __$GraphDatabase_prototype_getIndexedRelationship__12() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationship__12() {


              return __this.getIndexedRelationships(index, property, value, __cb(_, __frame, 3, 24, function ___(__0, __1) { relationships = __1;
                return _(null, ((((relationships != null) ? relationships[0] : void 0)) || null)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationship__12() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    GraphDatabase.prototype.getIndexedRelationships = function GraphDatabase_prototype_getIndexedRelationships__13(index, property, value, _) { var key, response, services, url, val, _this, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedRelationships__13", line: 209 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedRelationships__13, 3, __frame, function __$GraphDatabase_prototype_getIndexedRelationships__13() { _this = __this; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationships__13() {



              return __this.getServices(__cb(_, __frame, 4, 19, function ___(__0, __1) { services = __1;
                key = encodeURIComponent(property);
                val = encodeURIComponent(value);
                url = ((((((("" + services.relationship_index) + "/") + index) + "/") + key) + "/") + val);
                return __this._request.get(url, __cb(_, __frame, 8, 19, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map(function(relationship) {
                    return new Relationship(_this, relationship); })); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationships__13() { if (error) {


                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };







    GraphDatabase.prototype.query = function GraphDatabase_prototype_query__14(query, params, _) { var body, columns, endpoint, i, map, response, results, row, services, value, _ref, _ref1, __this = this; var __frame = { name: "GraphDatabase_prototype_query__14", line: 233 }; return __func(_, this, arguments, GraphDatabase_prototype_query__14, 2, __frame, function __$GraphDatabase_prototype_query__14() {

        if ((params == null)) {
          params = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_query__14() {


              return __this.getServices(__cb(_, __frame, 6, 19, function ___(__0, __2) { services = __2;
                endpoint = (services.cypher || ((((_ref = services.extensions) != null) ? (((_ref1 = _ref.CypherPlugin) != null) ? _ref1["execute_query"] : void 0) : void 0)));
                if (!endpoint) {
                  return _(new Error("Cypher plugin not installed")); } ;

                return __this._request.post({
                  uri: endpoint,
                  json: {
                    query: query,
                    params: params } }, __cb(_, __frame, 11, 19, function ___(__0, __3) { response = __3;


                  if ((response.statusCode === status.NO_CONTENT)) {
                    return _(new Error((("Unknown Neo4j error for query:\n\n" + query) + "\n"))); } ;

                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  body = response.body;
                  columns = body.columns;














                  return (function __1(_) { var _i, _j, _len, _len1, _ref2, _results; _ref2 = body.data; _results = []; for (_i = 0, _len = _ref2.length; (_i < _len); _i++) { row = _ref2[_i]; map = { }; for (i = _j = 0, _len1 = row.length; (_j < _len1); i = ++_j) { value = row[i]; map[columns[i]] = util.transform(value, __this); }; _results.push(map); }; return _(null, _results); })(__cb(_, __frame, 40, 18, function ___(__0, __4) { results = __4;
                    return _(null, results); }, true)); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_query__14() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.query = function(query, params, callback) {
        if (((typeof query === "function") && (typeof params === "string"))) {
          console.warn((("neo4j.GraphDatabase::query()’s signature is " + "now (query, params, callback). Please update your code!\n") + new Error().stack.split("\n")[2]));
          callback = query;
          query = params;
          params = null; }
         else if ((typeof params === "function")) {
          callback = params;
          params = null; }  ;

        return actual.call(this, query, params, callback); };

    })(GraphDatabase.prototype.query);

    GraphDatabase.prototype.execute = function GraphDatabase_prototype_execute__15(script, params, _) { var endpoint, response, services, _ref, _ref1, __this = this; var __frame = { name: "GraphDatabase_prototype_execute__15", line: 295 }; return __func(_, this, arguments, GraphDatabase_prototype_execute__15, 2, __frame, function __$GraphDatabase_prototype_execute__15() {

        if ((params == null)) {
          params = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_execute__15() {


              return __this.getServices(__cb(_, __frame, 6, 19, function ___(__0, __1) { services = __1;
                endpoint = (((_ref = services.extensions) != null) ? (((_ref1 = _ref.GremlinPlugin) != null) ? _ref1["execute_script"] : void 0) : void 0);
                if (!endpoint) {
                  return _(new Error("Gremlin plugin not installed")); } ;

                return __this._request.post({
                  uri: endpoint,
                  json: {
                    script: script,
                    params: params } }, __cb(_, __frame, 11, 19, function ___(__0, __2) { response = __2;


                  if ((response.statusCode === status.NO_CONTENT)) {
                    return _(new Error((("Unknown Neo4j error for Gremlin script:\n\n" + script) + "\n"))); } ;

                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, util.transform(response.body, __this)); }, true)); }, true)); }); })(function ___(error, __result) { __tryCatch(_, function __$GraphDatabase_prototype_execute__15() { if (error) {

                return _(adjustError(error)); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.execute = function(script, params, callback) {
        if ((typeof params === "function")) {
          callback = params;
          params = null; } ;

        return actual.call(this, script, params, callback); };

    })(GraphDatabase.prototype.execute);

    return GraphDatabase;

  }).call(this);

}).call(this);