/*** Generated by streamline 0.4.5 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename); (function() {
  var Path;

  module.exports = Path = (function() {
    var get, set, _this = this;


    function Path(start, end, length, nodes, relationships) {
      this._start = start;
      this._nodes = nodes;
      this._length = length;
      this._relationships = relationships;
      this._end = end; };






    get = function(props) {
      var getter, name, _results;
      _results = [];
      for (name in props) {
        getter = props[name];
        _results.push(Path.prototype.__defineGetter__(name, getter)); };

      return _results; };


    set = function(props) {
      var name, setter, _results;
      _results = [];
      for (name in props) {
        setter = props[name];
        _results.push(Path.prototype.__defineSetter__(name, setter)); };

      return _results; };






    get({
      start: function() {
        return (this._start || null); } });



    get({
      end: function() {
        return (this._end || null); } });



    get({
      length: function() {
        return (this._length || 0); } });



    get({
      nodes: function() {
        return (this._nodes || []); } });



    get({
      relationships: function() {
        return (this._relationships || []); } });



    return Path;

  }).call(this);

}).call(this);